# Generated by Fluxline - a starting point, not a maintained best-practices Dockerfile.
# Edit freely; Fluxline only regenerates this file if you ask it to.
FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm ci && npm run build
EXPOSE 8080
CMD npm start
