// Generated by Fluxline - edit the pipeline in the builder, not this file.
pipeline {
  agent any
  stages {
    stage('Source') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'npm ci && npm run build'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
    stage('Security Scan') {
      steps {
        sh 'docker run --rm -v $(pwd):/work aquasec/trivy:latest \'fs\' --severity \'CRITICAL,HIGH\' --exit-code 1 /work'
      }
    }
    stage('Package') {
      steps {
        withCredentials([string(credentialsId: 'docker_secret', variable: 'docker_secret')]) {
          sh 'docker login -u \'orslon\' -p "$docker_secret" \'docker.io\''
          sh 'docker build -t \'orslon/testing-app\':$BUILD_NUMBER .'
          sh 'docker push \'orslon/testing-app\':$BUILD_NUMBER'
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'echo "Deployed orslon/testing-app:$BUILD_NUMBER"'
      }
    }
    stage('Notify') {
      steps {
        sh 'echo "Skipping Slack notify - no webhook configured"'
      }
    }
  }
}
