# SonarQube/SonarCloud project config
# Replace values below with your actual SonarCloud org + project key

sonar.projectKey=orslon_Testing
sonar.organization=orslon
sonar.projectName=Testing
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-reporter.xml

sonar.exclusions=node_modules/**,coverage/**
